// Code generated by aws-mocker; DO NOT EDIT.

package examplemock

import (
	"context"

	awsmiddle "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/sts"
	"github.com/aws/smithy-go/middleware"
)

type DynamoDBMock struct {
	callCount               map[string]int
	batchGetItemMockReturns BatchGetItemReturns
	listTablesMockReturns   ListTablesReturns
}

func NewDynamoDBMock() *DynamoDBMock {
	return &DynamoDBMock{
		callCount: make(map[string]int),
	}
}

func (d *DynamoDBMock) GetCallCount() map[string]int {
	return d.callCount
}

type BatchGetItemReturns struct {
	Return dynamodb.BatchGetItemOutput
	Error  error
}

func (d *DynamoDBMock) SetBatchGetItemReturn(o dynamodb.BatchGetItemOutput) {
	d.batchGetItemMockReturns.Return = o
}

func (d *DynamoDBMock) SetBatchGetItemError(e error) {
	d.batchGetItemMockReturns.Error = e
}

type ListTablesReturns struct {
	Return dynamodb.ListTablesOutput
	Error  error
}

func (d *DynamoDBMock) SetListTablesReturn(o dynamodb.ListTablesOutput) {
	d.listTablesMockReturns.Return = o
}

func (d *DynamoDBMock) SetListTablesError(e error) {
	d.listTablesMockReturns.Error = e
}

func (d *DynamoDBMock) DynamoDBMiddlewareInjector() func(stack *middleware.Stack) error {
	return func(stack *middleware.Stack) error {
		return stack.Finalize.Add(
			middleware.FinalizeMiddlewareFunc(
				"DynamoDBMiddleware",
				func(ctx context.Context, input middleware.FinalizeInput, handler middleware.FinalizeHandler) (middleware.FinalizeOutput, middleware.Metadata, error) {
					switch awsmiddle.GetOperationName(ctx) {
					case "BatchGetItem":
						d.callCount["BatchGetItem"] += 1
						return middleware.FinalizeOutput{
							Result: &d.batchGetItemMockReturns.Return,
						}, middleware.Metadata{}, d.batchGetItemMockReturns.Error
					case "ListTables":
						d.callCount["ListTables"] += 1
						return middleware.FinalizeOutput{
							Result: &d.listTablesMockReturns.Return,
						}, middleware.Metadata{}, d.listTablesMockReturns.Error
					}

					return middleware.FinalizeOutput{}, middleware.Metadata{}, nil

				},
			),
			middleware.Before,
		)
	}
}

type STSMock struct {
	callCount                    map[string]int
	assumeRoleMockReturns        AssumeRoleReturns
	getCallerIdentityMockReturns GetCallerIdentityReturns
}

func NewSTSMock() *STSMock {
	return &STSMock{
		callCount: make(map[string]int),
	}
}

func (s *STSMock) GetCallCount() map[string]int {
	return s.callCount
}

type AssumeRoleReturns struct {
	Return sts.AssumeRoleOutput
	Error  error
}

func (s *STSMock) SetAssumeRoleReturn(o sts.AssumeRoleOutput) {
	s.assumeRoleMockReturns.Return = o
}

func (s *STSMock) SetAssumeRoleError(e error) {
	s.assumeRoleMockReturns.Error = e
}

type GetCallerIdentityReturns struct {
	Return sts.GetCallerIdentityOutput
	Error  error
}

func (s *STSMock) SetGetCallerIdentityReturn(o sts.GetCallerIdentityOutput) {
	s.getCallerIdentityMockReturns.Return = o
}

func (s *STSMock) SetGetCallerIdentityError(e error) {
	s.getCallerIdentityMockReturns.Error = e
}

func (s *STSMock) STSMiddlewareInjector() func(stack *middleware.Stack) error {
	return func(stack *middleware.Stack) error {
		return stack.Finalize.Add(
			middleware.FinalizeMiddlewareFunc(
				"STSMiddleware",
				func(ctx context.Context, input middleware.FinalizeInput, handler middleware.FinalizeHandler) (middleware.FinalizeOutput, middleware.Metadata, error) {
					switch awsmiddle.GetOperationName(ctx) {
					case "AssumeRole":
						s.callCount["AssumeRole"] += 1
						return middleware.FinalizeOutput{
							Result: &s.assumeRoleMockReturns.Return,
						}, middleware.Metadata{}, s.assumeRoleMockReturns.Error
					case "GetCallerIdentity":
						s.callCount["GetCallerIdentity"] += 1
						return middleware.FinalizeOutput{
							Result: &s.getCallerIdentityMockReturns.Return,
						}, middleware.Metadata{}, s.getCallerIdentityMockReturns.Error
					}

					return middleware.FinalizeOutput{}, middleware.Metadata{}, nil

				},
			),
			middleware.Before,
		)
	}
}
